command_timeout = 3600

add_newline = false

format = """
$os\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character
"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
blue = "#89b4fa"
black = "#13121a"
yellow = "#f9e2af"
mauve = "#cba6f7"
green = "#a6e3a1"
red = "#f38ba8"
text = "#cdd6f4"

[fill]
symbol = " "

[time]
time_format = "%H:%M"
style = "fg:blue bg:none"
format = "[ $time]($style)"

[os]
disabled = false
style = "bg:none fg:text"

[os.symbols]
Macos = ""
Debian = "󰣚"

[directory]
style = "blue"
format = "[ $path ]($style)"
truncation_length = 5

[git_branch]
symbol = " "
style = "fg:yellow bg:none"
format = 'on [$symbol$branch]($style)'

[git_status]
format = ' [($all_status$ahead_behind )]($style)'
stashed = '󰏗 '
ahead = '↑'
behind = '↓'
diverged = '↕'
untracked = '…'
staged = '●'
conflicted = '▲'
modified = '◆'
renamed = '→'
deleted = '✘'

[character]
success_symbol = '[➜](bold fg:green)'
error_symbol = '[➜](bold fg:red)'
vimcmd_symbol = '[](bold fg:yellow)'

[cmd_duration]
style = "fg:mauve bg:none"
format = "[󰔛 $duration]($style)"
show_notifications = true
min_time_to_notify = 45000
