os:
  edit: "nvim +{{line}} -- {{filename}}"

services:
  "bitbucket.dev.kiwigrid.com": "bitbucketServer:bitbucket.dev.kiwigrid.com"

promptToReturnFromSubprocess: false
notARepository: 'skip'   # 'prompt' | 'create' | 'skip' | 'quit'
keybinding:
  # optional: stop TAB from moving between panes
  universal:

    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextPage: <disabled>
    prevPage: <disabled>
    nextTab: '<tab>'
    prevTab: '<backtab>' # or '<shift-tab>' if your terminal sends that
