git:
  overrideGpg: true
gui:
  nerdFontsVersion: "3"
  # Mocha - Mauve
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

services:
  "bitbucket.dev.kiwigrid.com": "bitbucketServer:bitbucket.dev.kiwigrid.com"

promptToReturnFromSubprocess: false
notARepository: "skip" # 'prompt' | 'create' | 'skip' | 'quit'
keybinding:
  # optional: stop TAB from moving between panes
  universal:
    nextBlock-alt2: <disabled>
    prevBlock-alt2: <disabled>
    nextPage: <disabled>
    prevPage: <disabled>
    nextTab: "<tab>"
    prevTab: "<backtab>" # or '<shift-tab>' if your terminal sends that
